### ISSUE TITLE
Issue running meshery installation script in quick start guide

### ISSUE THREAD

**Issue by pranav-bhatt** [layer5io/meshery#2302]
#### Description

The [Meshery installation bash script](https://github.com/layer5io/meshery/blob/master/meshery) ends with the line `mesheryctl system start`. When run for the first time, the output generated is as shown below:
```
Extracting mesheryctl-v0.5.0-beta-1...
Archive:  /usr/bin/meshery.zip
  inflating: LICENSE                 
  inflating: README.md               
  inflating: mesheryctl              

Installing mesheryctl in /usr/local/bin.
mesheryctl installed.
permissions moved to pranav
Removing installation files and opening Meshery...Missing Meshery config file.
Create default config now [y/n]? EOF
```

#### Expected Behavior

Instead of waiting for user input (y/N), the script reads `EOF`, and exits.

[Line 99](https://github.com/layer5io/meshery/blob/566261f9f9618af1200a16ec593b327644e98d67/meshery#L99) should be moved out of the script, and the tutorials/docs should explicitly tell the user to run the `mesheryctl system start` command.

#### Environment:
- Host OS: Ubuntu 20.04
- Meshery Version: 0.5.0-beta-1
- Kubernetes Version: 1.20.2
- Browser: Firefox 84.0.2

#### To Reproduce
1. Follow steps in the [Meshery quick start guide](https://docs.meshery.io/installation/quick-start). Issue arises on the "Install Meshery" step.

**Comment by leecalcote** [comment]
Fixed by https://github.com/meshery/meshery/pull/2298

**Comment by pottekkat** [comment]
@pranav-bhatt The current flow is that when you run the bash script for installation, it would configure everything and start meshery server on your machine. 

But, when `system start` is first executed, there will not be any `config.yaml` file in your `~/home/.meshery` folder. So, it shows a prompt and the user should respond "y". This will create a new default `config.yaml` file and then meshery will proceed to start normally.

We have recently "silenced" this user confirmation through [this PR](https://github.com/meshery/meshery/pull/2298) from @hexxdump 

So, after this PR is merged, when installing through the bash script, it will not ask confirmation from the user and would proceed to create the `config.yaml` file.

**Comment by leecalcote** [comment]
#2298 should fix the defect described here. The change described in **Expected Behavior**, though, is slightly askew from our goal: short time to value; get users using Meshery quickly.

This installer is aimed at users looking to run Meshery. We want to make that happen fast. If we can delight users along the way, all the better. We really want to delight users with a single step download, install, deploy, run Meshery experience. See the [Preface and Guiding Principles of Command Design](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.z9ocaufuzael) in the Meshery CLI & Documentation.

As an option for advanced users, consideration for a `skip-run` (or similar) option in the bash script to forego starting `mesheryctl` could be made.

**Comment by navendu-pottekkat** [comment]
@pranav-bhatt Any updates on this issue? Were you able to work it out?

**Comment by pranav-bhatt** [comment]
Still facing the EOF issue, despite using the code in the mentioned PR.

**Comment by navendu-pottekkat** [comment]
Hmm, this might be an issue. Although I have almost the exact same setup as you apart from Kubernetes version 1.20.1. We will need to look into it. 

@hexxdump Could you please check this?

**Comment by hexxdump** [comment]
> Still facing the EOF issue, despite using the code in the mentioned PR. @leecalcote mentioned a PR by "The Piscean" (not sure what their GH username is) that fixes this though.

@pranav-bhatt,  Even after #2298 fix, you are hitting this issue?

**Comment by pranav-bhatt** [comment]
Sorry for the late reply. I tested this on various other platforms, and ignoring the fact that the release pulled doesn't have silent flag, it does the trick!
